language: python
sudo: false
python:
  - "3.4"
  - "3.5"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pycodestyle"
  - "pip install pylint"

script:
  - "coverage run --source=jpake setup.py test"
  - "pycodestyle jpake setup.py"
  - "pyflakes jpake setup.py"
  - "pylint -E jpake setup.py"

after_success:
  - "coveralls"

deploy:
  provider: pypi
  user: "bwhmather-travis"
  password:
    secure: "XbKadL2dsOMebMLAItb0CSXN6SBGUIud4lVOmL31+OD0CyGwUDNUQmDX25wwheWnoklxr7EStw3coWvKhi3qtA9H4qaUB1sx5lar/f6FN02d/9sT9DsDJh1LQBE+JbnevHcNXgtQVxuCvLKsdXAbAnRkgdQLzwjCkKiGU+3qXD8="
  on:
    branch: "master"
